import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { number } from '../services/api';

const purple = '#8262da';
const coral = '#ef8696';
const colors = ['#8466d9', '#e9bd68', '#eb8596'];
const axis = { tickLine: false, axisLine: false, tick: { fill: '#96919f', fontSize: 11 } };
const tip = { border: '1px solid #eeebf3', borderRadius: 10, fontSize: 12, boxShadow: '0 8px 30px #30224710' };

export function ActivityChart({ data }) { return <div className="chart activity-chart" aria-label="Test transactions grouped by time period"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.map(row => ({ ...row, period: row.label || `${row.hour}h` }))} margin={{ left: -20, right: 12, top: 12, bottom: 0 }}><defs><linearGradient id="area-purple" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={purple} stopOpacity={.2}/><stop offset="100%" stopColor={purple} stopOpacity={.015}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#efedf3"/><XAxis dataKey="period" {...axis} minTickGap={45}/><YAxis {...axis} tickFormatter={value => value >= 1000 ? `${(value / 1000).toFixed(1)}k` : value}/><Tooltip contentStyle={tip} labelFormatter={label => `Source period ${label}`} formatter={value => [number(value), 'Transactions']}/><Area type="monotone" dataKey="transactions" stroke={purple} strokeWidth={2.5} fill="url(#area-purple)"/></AreaChart></ResponsiveContainer></div>; }
export function ClassificationChart({ summary }) { const data = [{ name: 'Legitimate', value: summary.legitimate }, { name: 'Fraud flags', value: summary.fraud }]; return <div className="classification"><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius="76%" outerRadius="97%" startAngle={90} endAngle={-270} strokeWidth={0}>{data.map((item, index) => <Cell key={item.name} fill={[purple, coral][index]}/>)}</Pie><Tooltip contentStyle={tip} formatter={number}/></PieChart></ResponsiveContainer><div className="donut-label"><span>Flag rate</span><strong>{summary.fraud_percentage.toFixed(2)}<small>%</small></strong></div></div><div className="chart-legend">{data.map((item, index) => <div key={item.name}><span><i style={{ background: [purple, coral][index] }}/>{item.name}</span><strong>{number(item.value)}</strong></div>)}</div></div>; }
export function DistributionChart({ data, kind = 'probability' }) { return <div className="chart distribution-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ left: -20, right: 4, top: 10 }}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#efedf3"/><XAxis dataKey="label" {...axis} minTickGap={22}/><YAxis {...axis} tickFormatter={value => value >= 1000 ? `${Math.round(value / 1000)}k` : value}/><Tooltip contentStyle={tip} formatter={value => [number(value), 'Transactions']}/><Bar dataKey="count" radius={[5, 5, 0, 0]} maxBarSize={48}>{data.map((item, index) => <Cell key={item.label} fill={kind === 'risk' ? colors[['Low', 'Medium', 'High'].indexOf(item.label)] : index > 6 && kind === 'probability' ? '#eeb2bc' : '#af9ce8'}/>)}</Bar></BarChart></ResponsiveContainer></div>; }
export function CurveChart({ data, kind }) { const roc = kind === 'roc'; return <div className="chart curve-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: -12, right: 16, bottom: 20, top: 10 }}><CartesianGrid strokeDasharray="3 4" stroke="#efedf3"/><XAxis type="number" dataKey={roc ? 'fpr' : 'recall'} domain={[0, 1]} {...axis} label={{ value: roc ? 'False positive rate' : 'Recall', position: 'insideBottom', offset: -15, fill: '#96919f', fontSize: 11 }}/><YAxis domain={[0, 1]} {...axis}/><Tooltip contentStyle={tip}/><Line type="linear" dataKey={roc ? 'tpr' : 'precision'} name={roc ? 'True positive rate' : 'Precision'} dot={false} stroke={purple} strokeWidth={2.5}/></LineChart></ResponsiveContainer></div>; }
export function ThresholdChart({ data }) { return <div className="chart curve-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: -12, right: 12, bottom: 12 }}><CartesianGrid strokeDasharray="3 4" stroke="#efedf3"/><XAxis dataKey="threshold" type="number" domain={[0, 1]} {...axis}/><YAxis domain={[0, 1]} {...axis}/><Tooltip contentStyle={tip}/><Legend wrapperStyle={{ fontSize: 11 }}/><Line type="linear" dataKey="precision" stroke={purple} dot={false} strokeWidth={2}/><Line type="linear" dataKey="recall" stroke={coral} dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div>; }
