import { AlertCircle, ArrowUpRight, CheckCheck, FileSearch, LoaderCircle, ShieldAlert } from 'lucide-react';
import { number, percent, money } from '../services/api';

export function Loading({ text = 'Loading your workspace…' }) { return <div className="state" role="status"><LoaderCircle className="spin" size={26}/><p>{text}</p></div>; }
export function ErrorState({ error, retry }) { return <div className="error-box" role="alert"><AlertCircle size={20}/><div><strong>Something needs attention</strong><p>{error}</p>{retry && <button className="button secondary small" onClick={retry}>Try again</button>}</div></div>; }
export function Empty({ title = 'No predictions yet', text = 'Analyze a transaction or upload a CSV to start building your risk overview.', action }) { return <div className="state empty"><FileSearch size={32}/><h3>{title}</h3><p>{text}</p>{action}</div>; }
export function Badge({ value, className = '' }) { return <span className={`badge ${String(value).toLowerCase()} ${className}`}><span className="badge-dot"/>{value}</span>; }
export function PageHeading({ eyebrow, title, text, children }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div><div className="heading-actions">{children}</div></div>; }
export function Card({ title, subtitle, action, children, className = '' }) { return <section className={`card ${className}`}><div className="card-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>; }
export function Stat({ label, value, detail, icon: Icon = ShieldAlert, variant = '', footer }) { return <div className={`stat-card ${variant}`}><div className="stat-top"><span>{label}</span><div className="stat-icon"><Icon size={18}/></div></div><strong className="stat-number">{value}</strong><div className="stat-detail">{footer || <><span className="tiny-dot"/>{detail}</>}</div></div>; }
export function Threshold({ value, onChange, defaultValue, label = 'Fraud classification threshold', disabled = false }) { return <div className="threshold-control"><div className="flex justify-between gap-3"><label htmlFor="threshold-slider">{label}</label><strong>{Number(value).toFixed(4)}</strong></div><input id="threshold-slider" aria-label={label} type="range" disabled={disabled} min="0" max="1" step="0.001" value={value} onChange={event => onChange(Number(event.target.value))}/><div className="threshold-ends"><span>More flags · higher recall</span><span>Fewer flags · higher precision</span></div><button className="text-button" disabled={disabled} onClick={() => onChange(defaultValue)}>Reset to active default ({defaultValue.toFixed(4)})</button><p className="caption">The classification threshold is separate from the Low / Medium / High risk bands. Precision and recall trends are typical, not guaranteed on new data.</p></div>; }
export function PredictionTable({ rows, evaluation = false, currency = null }) { return <div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Amount</th><th>Fraud score</th><th>Risk level</th><th>Model decision</th>{evaluation && <th>Actual label</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || row.source_row || index}><td><div className="transaction-cell"><span className="transaction-icon">{row.prediction === 'Fraud' ? <ShieldAlert size={16}/> : <CheckCheck size={16}/>}</span><div><strong>{row.id ? `TX-${row.id.slice(0, 8).toUpperCase()}` : `ROW-${number(row.source_row ?? index + 1)}`}</strong><small>{row.created_at ? new Date(row.created_at).toLocaleString() : 'Held-out test transaction'}</small></div></div></td><td className="tabular">{money(row.amount ?? row.Amount, currency)}</td><td><div className="score-cell"><span>{percent(row.fraud_probability)}</span><div className="mini-track"><i style={{ width: `${row.fraud_probability * 100}%` }}/></div></div></td><td><Badge value={row.risk_level}/></td><td><span className={`decision ${row.prediction === 'Fraud' ? 'flagged' : ''}`}>{row.prediction === 'Fraud' ? '⚑ Fraud flag' : '✓ Legitimate'}</span></td>{evaluation && <td>{row.actual_class === 1 ? 'Fraud' : 'Legitimate'}</td>}</tr>)}</tbody></table></div>; }
export function LinkArrow({ children }) { return <span className="inline-link">{children}<ArrowUpRight size={15}/></span>; }
