import { useRef, useState } from 'react';
import { ArrowRight, CheckCircle2, Download, FileSpreadsheet, FileUp, Filter, LoaderCircle, Upload, X } from 'lucide-react';
import { API_BASE, downloadText, number, upload } from '../services/api';
import { Card, Empty, ErrorState, PageHeading, PredictionTable, Stat, Threshold } from '../components/ui';

export default function Batch({ model, notify }) {
  const [file, setFile] = useState(null), [preview, setPreview] = useState(null), [results, setResults] = useState(null);
  const [error, setError] = useState(null), [stage, setStage] = useState('idle'), [progress, setProgress] = useState(0);
  const [threshold, setThreshold] = useState(model.active_threshold), [filter, setFilter] = useState('All'), [page, setPage] = useState(1), [dragging, setDragging] = useState(false);
  const input = useRef(null);
  const busy = ['validating', 'scoring'].includes(stage);
  async function chooseFile(selected) {
    if (busy || !selected) return;
    setFile(null); setPreview(null); setResults(null); setError(null); setPage(1); setProgress(0); setStage('idle');
    if (!selected.name.toLowerCase().endsWith('.csv')) { setError('Choose a CSV file.'); return; }
    if (selected.size > model.limits.max_upload_bytes) { setError(`This file exceeds the ${model.limits.max_upload_bytes / 1024 / 1024} MB limit.`); return; }
    setFile(selected); setStage('validating');
    try { const data = await upload('/predict/batch/validate', selected, setProgress); setPreview(data); setStage('ready'); notify(`${number(data.rows)} transactions validated. Ready to analyze.`); }
    catch (error) { setError(error.message); setStage('idle'); }
  }
  async function score() {
    setStage('scoring'); setError(null); setProgress(0); setResults(null);
    try { const data = await upload(`/predict/batch?threshold=${threshold}`, file, setProgress); setResults(data); setStage('complete'); setPage(1); setFilter('All'); notify('Batch analysis complete. Results are ready to download.'); }
    catch (error) { setError(error.message); setStage('ready'); }
  }
  const filtered = results?.results.filter(row => filter === 'All' || row.prediction === filter) || [];
  const pages = Math.max(1, Math.ceil(filtered.length / 15));
  return <><PageHeading eyebrow="BATCH INTELLIGENCE" title="More transactions. One clear view." text="Validate, analyze and export a complete batch of transaction scores."><a className="button secondary" href={`${API_BASE}/sample-csv`} download><Download size={16}/> Sample CSV</a></PageHeading>
    <div className="stepper">{['Upload & validate', 'Review & analyze', 'Explore & export'].map((text, index) => <div key={text} className={(results ? 2 : preview ? 1 : 0) >= index ? 'current' : ''}><span>{index + 1}</span>{text}{index < 2 && <ArrowRight size={16}/>}</div>)}</div>
    {error && <ErrorState error={error}/>}<div className="batch-layout"><Card title="Upload transactions" subtitle="Every input is checked against the active model schema."><div className={`drop-zone ${dragging ? 'dragging' : ''}`} onDragOver={event => { event.preventDefault(); if (!busy) setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); chooseFile(event.dataTransfer.files[0]); }}><div className="upload-icon"><FileUp size={29}/></div><h3>Drop your CSV here</h3><p>or choose a file from your computer</p><button disabled={busy} className="button primary" onClick={() => input.current.click()}><Upload size={15}/> Browse files</button><small>CSV only · up to {model.limits.max_upload_bytes / 1024 / 1024} MB · {number(model.limits.max_batch_rows)} rows</small><input ref={input} aria-label="Upload transaction CSV" type="file" accept=".csv,text/csv" hidden disabled={busy} onChange={event => { chooseFile(event.target.files[0]); event.target.value = ''; }}/></div>
      {file && <div className="file-item"><FileSpreadsheet size={23}/><div><strong>{file.name}</strong><small>{(file.size / 1024).toFixed(1)} KB {preview && `· ${number(preview.rows)} transactions`}</small></div>{preview ? <CheckCircle2 size={19} className="success-text"/> : busy ? <LoaderCircle className="spin" size={18}/> : null}<button aria-label="Remove file" disabled={busy} className="icon-button" onClick={() => { setFile(null); setPreview(null); setResults(null); setError(null); setStage('idle'); }}><X size={16}/></button></div>}
      {busy && <div role="status" className="upload-progress"><div><span>{progress < 100 ? 'Uploading' : stage === 'validating' ? 'Validating structure' : 'Running model inference'}…</span><strong>{progress}% uploaded</strong></div><progress value={progress} max="100"/></div>}
      <p className="caption">Required: all {model.features.length} model feature columns. Leave individual values empty to use training imputation. Remove target labels ({model.dataset.target}), identifiers and extra columns before uploading. Raw Hugging Face rows can be converted with the preparation script in the README.</p><details className="schema-details"><summary>View required columns</summary><code>{model.features.map(f => f.name).join(', ')}</code></details>
    </Card><Card title="Analysis settings" subtitle="Apply a consistent threshold to this batch."><Threshold disabled={busy} value={threshold} onChange={value => { if (!busy) setThreshold(value); }} defaultValue={model.active_threshold}/><div className="notice">Risk bands remain at {model.risk_bands.medium} and {model.risk_bands.high}. Changing the classification threshold does not change the probability score.</div><button className="button primary full" disabled={!preview || busy} onClick={score}>{stage === 'scoring' ? <LoaderCircle className="spin" size={16}/> : <ArrowRight size={16}/>} {stage === 'scoring' ? 'Analyzing transactions…' : 'Run batch analysis'}</button><p className="caption">Results below retain the threshold used at scoring time. Running the batch again adds new records to live predictions.</p></Card></div>
    {preview && !results && <Card title="Validated preview" subtitle={`First ${preview.preview.length} of ${number(preview.rows)} rows · ${preview.imputed_cells} empty cells will be imputed`} className="table-card"><div className="table-wrap preview-table"><table><thead><tr>{preview.columns.map(name => <th key={name}>{name}</th>)}</tr></thead><tbody>{preview.preview.map((row, index) => <tr key={index}>{preview.columns.map(name => <td key={name}>{row[name] == null ? 'Missing' : typeof row[name] === 'number' ? Number(row[name].toFixed(4)) : row[name]}</td>)}</tr>)}</tbody></table></div></Card>}
    {results && <><div className="stats-grid batch-stats"><Stat label="Transactions scored" value={number(results.total)} detail={`Threshold ${results.threshold.toFixed(4)}`}/><Stat label="Fraud flags" value={number(results.fraud_count)} detail="Prioritize for review" variant="rose"/><Stat label="Legitimate predictions" value={number(results.legitimate_count)} detail="Below the selected threshold" variant="green"/><Stat label="Batch flag rate" value={`${results.fraud_percentage.toFixed(2)}%`} detail="Predicted flags, not actual fraud"/></div><Card title="Batch results" subtitle={`${number(filtered.length)} matching transactions · scores are not confirmed labels`} className="table-card" action={<div className="inline-actions"><Filter size={15}/><select aria-label="Filter batch results" value={filter} onChange={event => { setFilter(event.target.value); setPage(1); }} className="small-select"><option>All</option><option value="Fraud">Fraud flags</option><option>Legitimate</option></select><button className="button secondary small" onClick={() => downloadText(results.csv, 'sentinel-predictions.csv')}><Download size={14}/> Download CSV</button></div>}>{filtered.length ? <PredictionTable currency={model.dataset.currency} rows={filtered.slice((page - 1) * 15, page * 15)}/> : <Empty title="No matching transactions" text="Choose a different result filter."/>}<div className="pagination"><span>Page {page} of {pages}</span><div><button className="button secondary small" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>Previous</button><button className="button secondary small" disabled={page >= pages} onClick={() => setPage(value => value + 1)}>Next</button></div></div></Card></>}
  </>;
}
