import { useState } from 'react';
import { Award, CheckCircle2, Download, FlaskConical, Target } from 'lucide-react';
import { Card, PageHeading } from '../components/ui';
import { CurveChart, ThresholdChart } from '../components/charts';
import { downloadText, number, percent } from '../services/api';

export default function Performance({ model }) {
  const [partition, setPartition] = useState('validation');
  const metrics = model.metrics;
  const primaryMetric = model.selection_metric === 'f2' ? 'recall' : 'pr_auc';
  const labels = { accuracy: 'Accuracy', precision: 'Precision', recall: 'Recall', f1: 'F1 score', roc_auc: 'ROC-AUC', pr_auc: 'PR-AUC' };
  const cm = metrics.confusion_matrix;
  const maxImportance = Math.max(...model.feature_importance.map(row => Math.abs(row.importance)), 1e-12);
  return <><PageHeading eyebrow="MODEL OBSERVATORY" title="Confidence, backed by evidence." text="Measured performance on unseen data. Every metric has a source."><button className="button secondary" onClick={() => downloadText(JSON.stringify(model, null, 2), 'sentinel-model-report.json', 'application/json')}><Download size={16}/> Model report</button></PageHeading>
    <div className="model-banner"><div className="model-banner-icon"><Award size={27}/></div><div><div className="eyebrow">ACTIVE MODEL</div><h2>{model.model_name}</h2><p>{model.model_version} · trained {new Date(model.training_date).toLocaleDateString()}</p></div><div className="model-banner-right"><span><CheckCircle2 size={15}/> Validation selected</span><small>Active threshold {model.active_threshold.toFixed(4)}</small></div></div>
    <div className="metrics-grid">{Object.entries(labels).map(([key, label]) => <div key={key} className={`metric-card ${key === primaryMetric ? 'featured' : ''}`}><span>{label}{key === primaryMetric && <Target size={15}/>}</span><strong>{percent(metrics[key])}</strong><small>{key === primaryMetric ? (primaryMetric === 'recall' ? 'Fraud-class coverage · F2 selection' : 'Primary ranking metric · AP') : 'Held-out test set'}</small></div>)}</div>
    <div className="notice"><FlaskConical size={17}/><span>Test set: {number(model.dataset.splits.test.rows)} transactions, {number(model.dataset.splits.test.fraud)} actual fraud cases. PR-AUC is computed as average precision. Test results did not choose the model.</span></div>
    <div className="performance-grid"><Card title="Precision–recall curve" subtitle="Fraud detection quality under severe imbalance"><CurveChart data={model.curves.precision_recall} kind="pr"/></Card><Card title="ROC curve" subtitle="True positive rate against false positive rate"><CurveChart data={model.curves.roc} kind="roc"/></Card><Card title="Confusion matrix" subtitle="Actual rows × predicted columns · held-out test"><div className="confusion-matrix"><div/><span>Pred. legitimate</span><span>Pred. fraud</span><span>Actual<br/>legitimate</span><div className="correct"><strong>{number(cm[0][0])}</strong><small>True negatives</small></div><div className="mistake"><strong>{number(cm[0][1])}</strong><small>False positives</small></div><span>Actual<br/>fraud</span><div className="mistake"><strong>{number(cm[1][0])}</strong><small>False negatives</small></div><div className="correct"><strong>{number(cm[1][1])}</strong><small>True positives</small></div></div><p className="caption matrix-caption">False positives add review friction. False negatives leave fraud undetected.</p></Card></div>
    <Card title="The model comparison" subtitle={`Parameters tuned with 3-fold ${model.training.cv_strategy || 'stratified'} CV. Finalists fit the full training partition.`} action={<div className="segmented compact"><button className={partition === 'validation' ? 'active' : ''} onClick={() => setPartition('validation')}>Validation</button><button className={partition === 'test' ? 'active' : ''} onClick={() => setPartition('test')}>Test</button></div>} className="table-card"><div className="table-wrap"><table><thead><tr><th>Model / imbalance strategy</th><th>CV AP</th><th>F2 score</th>{Object.values(labels).map(label => <th key={label}>{label}</th>)}<th>Threshold</th></tr></thead><tbody>{model.comparison.map(row => <tr key={row.name} className={row.selected ? 'selected-model' : ''}><td><strong>{row.name} {row.selected && <span className="selected-tag">Selected</span>}</strong><small>{row.imbalance_strategy}</small></td><td>{percent(row.cv_pr_auc)}</td><td>{percent(row[partition].f2)}</td>{Object.keys(labels).map(key => <td key={key}>{percent(row[partition][key])}</td>)}<td>{row.threshold.toFixed(row.threshold > .9999 ? 6 : 4)}</td></tr>)}</tbody></table></div><p className="table-note">{model.selection_rule}{model.training_class_counts && <> Fraud training rows: {number(model.training_class_counts.before['1'])} → {number(model.training_class_counts.after['1'])} after sampling. Validation and test prevalence remain unchanged.</>}</p></Card>
    <div className="two-columns"><Card title="Which features carry the most signal?" subtitle={model.importance_method}><div className="importance-list">{model.feature_importance.slice(0, 12).map(row => <div key={row.feature}><span>{row.feature}</span><div className="importance-track"><i style={{ width: `${Math.abs(row.importance) / maxImportance * 100}%` }}/></div><strong>{row.importance.toFixed(4)}</strong></div>)}</div><p className="caption">Global associations in the model; importance does not establish causation.</p></Card><Card title="Choose the review trade-off" subtitle="Validation precision & recall across thresholds"><ThresholdChart data={model.threshold_curve}/><div className="threshold-fact"><Target size={22}/><div><strong>{model.selected_threshold.toFixed(4)} <span>validation-selected threshold</span></strong><p>Maximizes F2{model.minimum_validation_recall ? ` subject to at least ${percent(model.minimum_validation_recall, 0)} validation recall` : ', giving recall more weight than precision'}.</p></div></div><p className="caption">{model.minimum_validation_recall ? 'The recall target applies to validation data; test and future recall can differ.' : 'The threshold is selected on validation data; test and future recall can differ.'} Changing the threshold on the prediction pages affects new decisions. Reported test metrics remain tied to the original validation-selected threshold.</p></Card></div>
    <div className="methodology"><h3>How this benchmark was built</h3><div><p><strong>01 / Split before learning</strong>Duplicates removed, then {model.dataset.split_strategy || 'stratified'} 60/20/20 train/validation/test partitions. No shared rows.</p><p><strong>02 / Keep resampling inside training</strong>Imputation, scaling and resampling are fitted within each CV fold. Tuning uses {number(model.training.tuning_rows)} training rows.</p><p><strong>03 / Keep the limits visible</strong>{model.probability_note} Deployment needs validation on its own transaction data, calibration and monitoring.</p></div></div>
  </>;
}
